# Generated by Django 4.2.1 on 2023-05-12 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='email',
        ),
        migrations.RemoveField(
            model_name='students',
            name='name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='password',
        ),
    ]
