# Generated by Django 4.2.1 on 2023-06-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_alter_students_birth_certificate_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='staffs',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='staffs', to='student_management_app.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school_segment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
