# Generated by Django 4.2.1 on 2023-05-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_alter_attendance_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportstaffs',
            name='leave_status',
            field=models.IntegerField(default=0),
        ),
    ]
