# Generated by Django 4.2.1 on 2023-06-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_remove_subject_staff_id_staffs_subjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='service_type',
            field=models.CharField(blank=True, default='school', max_length=100),
        ),
    ]
