# Generated by Django 4.2.1 on 2023-06-22 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_students_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('agenda', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='staffs',
            name='availability',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='staffs',
            name='background_check',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='staffs',
            name='date_of_birth',
            field=models.DateField(blank=True, default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='staffs',
            name='personal_statement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='preferred_grade_level',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='staffs',
            name='salary_expectations',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_expertise', models.TextField()),
                ('teaching_methods', models.TextField()),
                ('professional_development', models.TextField()),
                ('language_proficiency', models.TextField()),
                ('technology_skills', models.TextField()),
                ('special_skills', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.staffs')),
            ],
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.staffs')),
            ],
        ),
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('teaching_experience', models.IntegerField()),
                ('educational_qualification', models.CharField(max_length=255)),
                ('certification', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.staffs')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employment_history', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.staffs')),
            ],
        ),
        migrations.CreateModel(
            name='Attendees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.meetings')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.staffs')),
            ],
        ),
    ]
