# Generated by Django 4.2.1 on 2023-05-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_alter_leavereportstudent_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='fcm_token',
            field=models.TextField(default=''),
        ),
    ]
